test:
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>

local:
  service: Disk
  root: <%= Rails.root.join("storage") %>

# Use bin/rails credentials:edit to set the AWS secrets (as aws:access_key_id|secret_access_key)
spaces:
  service: S3
  access_key_id: <%= Figaro.env.spaces_access_key_id %>
  secret_access_key: <%= Figaro.env.spaces_secret_access_key %>
  region: nyc3
  bucket: budgit-app
  endpoint: https://nyc3.digitaloceanspaces.com/

cloudinary:
  service: Cloudinary
  cloud_name: deyemiobaa
  api_key: <%= Figaro.env.cloud_api_key %>
  api_secret: <%= Figaro.env.cloud_api_secret %>
# Remember not to checkin your GCS keyfile to a repository
# google:
#   service: GCS
#   project: your_project
#   credentials: <%= Rails.root.join("path/to/gcs.keyfile") %>
#   bucket: your_own_bucket-<%= Rails.env %>

# Use bin/rails credentials:edit to set the Azure Storage secret (as azure_storage:storage_access_key)
# microsoft:
#   service: AzureStorage
#   storage_account_name: your_account_name
#   storage_access_key: <%= Rails.application.credentials.dig(:azure_storage, :storage_access_key) %>
#   container: your_container_name-<%= Rails.env %>

# mirror:
#   service: Mirror
#   primary: local
#   mirrors: [ amazon, google, microsoft ]
